/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as CreateReviewRouteImport } from './routes/create/review'
import { Route as DSlugRouteImport } from './routes/d/$slug'
import { Route as DealsIndexRouteImport } from './routes/deals/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoDealRouteImport } from './routes/demo/deal'
import { Route as DemoSetupRouteImport } from './routes/demo/setup'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DealsIdIndexRouteImport } from './routes/deals/$id/index'
import { Route as DealsIdPublishedRouteImport } from './routes/deals/$id/published'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReviewRoute = CreateReviewRouteImport.update({
  id: '/create/review',
  path: '/create/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDealRoute = DemoDealRouteImport.update({
  id: '/demo/deal',
  path: '/demo/deal',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSetupRoute = DemoSetupRouteImport.update({
  id: '/demo/setup',
  path: '/demo/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIdIndexRoute = DealsIdIndexRouteImport.update({
  id: '/deals/$id/',
  path: '/deals/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIdPublishedRoute = DealsIdPublishedRouteImport.update({
  id: '/deals/$id/published',
  path: '/deals/$id/published',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create/review': typeof CreateReviewRoute
  '/d/$slug': typeof DSlugRoute
  '/demo/deal': typeof DemoDealRoute
  '/demo/setup': typeof DemoSetupRoute
  '/create/': typeof CreateIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/deals/$id/published': typeof DealsIdPublishedRoute
  '/deals/$id/': typeof DealsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create/review': typeof CreateReviewRoute
  '/d/$slug': typeof DSlugRoute
  '/demo/deal': typeof DemoDealRoute
  '/demo/setup': typeof DemoSetupRoute
  '/create': typeof CreateIndexRoute
  '/deals': typeof DealsIndexRoute
  '/demo': typeof DemoIndexRoute
  '/docs': typeof DocsIndexRoute
  '/deals/$id/published': typeof DealsIdPublishedRoute
  '/deals/$id': typeof DealsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create/review': typeof CreateReviewRoute
  '/d/$slug': typeof DSlugRoute
  '/demo/deal': typeof DemoDealRoute
  '/demo/setup': typeof DemoSetupRoute
  '/create/': typeof CreateIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/deals/$id/published': typeof DealsIdPublishedRoute
  '/deals/$id/': typeof DealsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create/review'
    | '/d/$slug'
    | '/demo/deal'
    | '/demo/setup'
    | '/create/'
    | '/deals/'
    | '/demo/'
    | '/docs/'
    | '/deals/$id/published'
    | '/deals/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create/review'
    | '/d/$slug'
    | '/demo/deal'
    | '/demo/setup'
    | '/create'
    | '/deals'
    | '/demo'
    | '/docs'
    | '/deals/$id/published'
    | '/deals/$id'
  id:
    | '__root__'
    | '/'
    | '/create/review'
    | '/d/$slug'
    | '/demo/deal'
    | '/demo/setup'
    | '/create/'
    | '/deals/'
    | '/demo/'
    | '/docs/'
    | '/deals/$id/published'
    | '/deals/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateReviewRoute: typeof CreateReviewRoute
  DSlugRoute: typeof DSlugRoute
  DemoDealRoute: typeof DemoDealRoute
  DemoSetupRoute: typeof DemoSetupRoute
  CreateIndexRoute: typeof CreateIndexRoute
  DealsIndexRoute: typeof DealsIndexRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DealsIdPublishedRoute: typeof DealsIdPublishedRoute
  DealsIdIndexRoute: typeof DealsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/review': {
      id: '/create/review'
      path: '/create/review'
      fullPath: '/create/review'
      preLoaderRoute: typeof CreateReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/deal': {
      id: '/demo/deal'
      path: '/demo/deal'
      fullPath: '/demo/deal'
      preLoaderRoute: typeof DemoDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/setup': {
      id: '/demo/setup'
      path: '/demo/setup'
      fullPath: '/demo/setup'
      preLoaderRoute: typeof DemoSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$id/': {
      id: '/deals/$id/'
      path: '/deals/$id'
      fullPath: '/deals/$id/'
      preLoaderRoute: typeof DealsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$id/published': {
      id: '/deals/$id/published'
      path: '/deals/$id/published'
      fullPath: '/deals/$id/published'
      preLoaderRoute: typeof DealsIdPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateReviewRoute: CreateReviewRoute,
  DSlugRoute: DSlugRoute,
  DemoDealRoute: DemoDealRoute,
  DemoSetupRoute: DemoSetupRoute,
  CreateIndexRoute: CreateIndexRoute,
  DealsIndexRoute: DealsIndexRoute,
  DemoIndexRoute: DemoIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DealsIdPublishedRoute: DealsIdPublishedRoute,
  DealsIdIndexRoute: DealsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
